"""
Inventory section — L1 Inventory signals.

Three tabs:
  - Where is the market under-supplying? (the proof-of-template tab)
  - What's stuck and not selling?
  - Which sizes are quietly being abandoned?
"""
import streamlit as st
from lib.styles import inject_global_styles
from lib.components import section_header, why_matters, todays_read, stub_block


inject_global_styles()

section_header(
    eyebrow="Section \u00b7 L1 Inventory signals",
    title="Inventory",
    intro="What's moving fast, what's stuck, and what brands are quietly "
          "abandoning. Demand revelation, derived from variant-level stockout "
          "and restock observations across every brand we track.",
)

tab1, tab2, tab3 = st.tabs([
    "Where is the market under-supplying?",
    "What's stuck and not selling?",
    "Which sizes are quietly being abandoned?",
])

with tab1:
    why_matters(
        "Sizes and colours that stock out fast while others sit untouched "
        "reveal what the market actually wants \u2014 vs what brands chose "
        "to produce. The same pattern showing up across multiple brands "
        "isn't a one-brand mistake; it's a market-wide manufacturing blind "
        "spot you can exploit either by stocking those sizes, securing them "
        "early from suppliers, or pricing them above the category median."
    )

    # In v1 the dynamic conclusion is a placeholder. In week 2 this paragraph
    # is generated by a daily query against L1\u00b711 Size Asymmetry Stockout
    # outputs that fills the slots in a fixed template.
    todays_read(
        "Stockout-velocity calculations begin in week 2 once L1\u00b711 (Size "
        "Asymmetry Stockout) is wired into the scraper's nightly job. Once "
        "the signal fires, this paragraph updates daily with the dominant "
        "category, hot sizes, cold sizes, and the action recommendation."
    )

    stub_block("Heatmap + asymmetry index + opportunities table shipping in week 2.")

with tab2:
    why_matters(
        "Products at deep discount with all variants still in stock for 30+ "
        "days are dead stock \u2014 a design, fabric, or fit failure that's "
        "eating warehouse space. Knowing what's dying across the market tells "
        "you what to avoid producing or stocking."
    )
    stub_block("Detailed view shipping in week 3 \u2014 see roadmap.")

with tab3:
    why_matters(
        "When a brand stops restocking specific sizes (say, 38 and 40) while "
        "continuing to replenish others, they're abandoning that size \u2014 "
        "a silent customer-mix shift. Catching this early reveals where "
        "competitors are moving their bets."
    )
    stub_block("Detailed view shipping in week 3 \u2014 see roadmap.")
